"""g46_add_user_theme_pref

Revision ID: 330f1633b5b9
Revises: g38admin0001
Create Date: 2026-06-12 18:53:05.063620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330f1633b5b9'
down_revision: Union[str, None] = 'g38admin0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme_pref', sa.String(length=8), server_default='light', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme_pref')
    # ### end Alembic commands ###
