"""add avatar columns

Revision ID: 882d30e0b3ce
Revises: 8669645e44d8
Create Date: 2026-05-02 23:37:38.047506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882d30e0b3ce'
down_revision: Union[str, None] = '8669645e44d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_data', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('avatar_content_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_content_type')
    op.drop_column('users', 'avatar_data')
    # ### end Alembic commands ###
